image: Visual Studio 2017

environment:
  nodejs_version: "11"

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - ps: Install-Product node $env:nodejs_version x64
  - npm install
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains('[publish binary]')) { node-pre-gyp package; node-pre-gyp-github publish }
